name: Docs to PDF

on:
  push:
    branches:
      - master

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: src
          output_dir: pdfs
          images_dir: src/images
          image_import: ./images
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: nectar-whitepaper
          path: pdfs/nectar-whitepaper.pdf